# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=0)),
                ('day', models.SmallIntegerField(default=0)),
                ('month', models.SmallIntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('timeStart', models.IntegerField(default=0)),
                ('timeEnd', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=2044)),
            ],
        ),
    ]
