# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20170810_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
