FROM alpine:latest

RUN adduser -D -u 1000 firik -h /home/firik
WORKDIR /home/firik

RUN apk add --update python3 bash wget
RUN wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py

RUN python3 get-pip.py
RUN pip install virtualenv
USER firik
RUN mkdir venv
RUN virtualenv venv

RUN $HOME/venv/bin/pip install Django
VOLUME ["/home/firik/app"]

ENTRYPOINT ["bash"]

EXPOSE 4200