version: '3.3'
services:
  # mysql_db:
  #   image: mysql
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #     MYSQL_DATABASE: todo_inc
  #     MYSQL_USER: firik
  #     MYSQL_PASSWORD: 123456
  #   container_name: mysql

  backend:
    image: docker_backend
    build: 
      context: ./
      dockerfile: Dockerfile_django
    command: python3 manage.py runserver 0.0.0.0:8000
    # command: bash
    volumes:
      - ../django_backend/.:/home/firik/app/django_backend
    ports:
      - "8000:8000"
    # depends_on:
      # - mysql_db
    container_name: django

  # angular:
  #   build: 
  #     context: ./
  #     dockerfile: Dockerfile_angular2
  #   image: angular2
  #   volumes:
  #     - ../ngfiles/.:/home/firik/app/ngfiles
  #   container_name: angular2
  #   command: npm start
    
volumes:
  db_data: