FROM alpine:latest

RUN apk add --update python3 bash wget
RUN mkdir -p /home/firik/app/django_backend
WORKDIR /home/firik

RUN wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py

RUN python3 get-pip.py

WORKDIR /home/firik/app/django_backend
RUN pip install Django
VOLUME ["/home/firik/app/django_backend"]

EXPOSE 8000