version: '3.3'
services:
#   mysql_db:
#     image: mysql
#     volumes:
#       - db_data:/var/lib/mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: 123456
#       MYSQL_DATABASE: todo_inc
#       MYSQL_USER: firik
#       MYSQL_PASSWORD: 123456
#     container_name: mysql
#     networks:
#       app_net:
#         ipv4_address: 175.18.18.3

  postgresql_db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_USER: dock_djan
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: todo_inc
    container_name: postgresql
    networks:
      app_net:
        ipv4_address: 175.18.18.6
    ports:
      - "5432:5432"

  backend:
    image: firik/django_backend:0.0.4
#    build:
#      context: ./
#      dockerfile: Dockerfile_django
    command: bash -c "source ../venv/bin/activate && python3 manage.py runserver 0.0.0.0:8000"
#    command: bash
    volumes:
      - /home/firik/apps/angular-django/task_backend:/home/dock_djan/task_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgresql_db
    container_name: django_backend
    networks:
      app_net:
        ipv4_address: 175.18.18.5
    # tty: true

  angular:
    build: 
      context: ./
      dockerfile: Dockerfile_angular2
    image: angular2
    volumes:
      - /home/firik/apps/angular-django/ngfiles:/home/firik/app/ngfiles
    container_name: angular2
    command: npm start
    ports:
      - "4201:4201"
    networks:
      app_net:
        ipv4_address: 175.18.18.2
        
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 175.18.18.0/24

volumes:
  db_data: